/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ypan_umtest_SelfUninstall */

#ifndef _Included_com_ypan_umtest_SelfUninstall
#define _Included_com_ypan_umtest_SelfUninstall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ypan_umtest_SelfUninstall
 * Method:    startWork
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ypan_umtest_SelfUninstall_startWork
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
